Repository hyperledger-labs/orion-server, pull requests merged in 2021-08, with the labels that each got.

#119 Replicator static cluster unit test
  go.mod
  go.sum
  internal/replication/blockreplicator.go
  internal/replication/blockreplicator_3node_test.go
  internal/replication/blockreplicator_test.go
  internal/replication/env_test.go
Labels: replication

#142 Flaky test: blockreplicator
  internal/replication/blockreplicator_test.go
Labels: bug

#54 Order preserving encoding of +ve/-ve value of indexed attribute
  go.mod
  internal/stateindex/encoding.go
  internal/stateindex/encoding_test.go
  internal/stateindex/index_entries.go
  internal/stateindex/index_entries_test.go
Labels: query support

#144 Flaky test: block replicator timeout
  internal/replication/blockreplicator_test.go
Labels: bug

#130 Remove second unmarshall in mptrie store GetNode call
  internal/mptrie/mptrie_test.go
  internal/mptrie/store/open.go
  internal/mptrie/store/update_and_query.go
Labels: performance

#131 expose leveldb iterator needed to execute range queries on index
  go.mod
  go.sum
  internal/worldstate/db.go
  internal/worldstate/leveldb/commit_and_query.go
  internal/worldstate/leveldb/commit_and_query_test.go
  internal/worldstate/leveldb/persisted_value.pb.go
  internal/worldstate/leveldb/persisted_value.proto
  pkg/types/block_and_transaction.pb.go
  protos/block_and_transaction.proto
Labels: query support

#149 Allow config updates to Admins & CAs
  internal/replication/blockreplicator.go
  internal/replication/blockreplicator_test.go
  internal/replication/env_test.go
  internal/replication/utils.go
Labels: replication

#132 Update index entries structure
  internal/blockprocessor/committer.go
  internal/blockprocessor/committer_test.go
  internal/stateindex/index_entries.go
  internal/stateindex/index_entries_test.go
Labels: query support

#150 Mark dynamic config invalid
  internal/blockprocessor/config_tx_validator.go
  internal/blockprocessor/config_tx_validator_test.go
  internal/blockprocessor/validator_test.go
Labels: replication

#160 Remove ValidationInfo from Block
  pkg/types/block_and_transaction.pb.go
  protos/block_and_transaction.proto
Labels: bug
