Repository hyperledger-labs/orion-server, pull requests merged in 2021-07, with the labels that each got.

#96 signer utility
  Makefile
  cmd/signer/signer.go
  cmd/signer/signer_test.go
  pkg/cryptoservice/signer.go
Labels: documentation

#79 base doc file
  README.md
  deployment/sample/bootstrap-shared-config.yaml
  deployment/sample/config-sample.yml
  deployment/sample/crypto/CA/CA.key
  deployment/sample/crypto/CA/CA.pem
  deployment/sample/crypto/admin/admin.key
  deployment/sample/crypto/admin/admin.pem
  deployment/sample/crypto/alice/alice.key
  deployment/sample/crypto/alice/alice.pem
  deployment/sample/crypto/bob/bob.key
  deployment/sample/crypto/bob/bob.pem
  deployment/sample/crypto/server/server.key
  deployment/sample/crypto/server/server.pem
  docs/README.md
  docs/curl/build.md
  docs/curl/config.md
  docs/curl/configtx.md
  docs/curl/crypto.md
  docs/curl/datatx.md
  docs/curl/dbtx.md
  docs/curl/errors.md
  docs/curl/query.md
  docs/curl/usertx.md
  docs/figures/high-level-architecture.png
  figures/Architecture.gif
  figures/LedgerMerkleTree.gif
  figures/TxFlow.gif
  figures/cycle.png
  figures/parallel.png
  figures/reorder.png
  figures/rw-dependency.png
  figures/sprint1.png
  figures/sprint2.png
  figures/sprint3.png
  figures/sprint4.png
  figures/sprint5.png
Labels: documentation

#113 fix dbupdates
  internal/bcdb/ledger_query_procesor_test.go
  internal/bcdb/transaction_processor_test.go
  internal/bcdb/worldstate_query_processor_test.go
  internal/blockprocessor/committer.go
  internal/blockprocessor/committer_test.go
  internal/blockprocessor/config_tx_validator_test.go
  internal/blockprocessor/data_tx_validator_test.go
  internal/blockprocessor/dbadmin_tx_validator_test.go
  internal/blockprocessor/processor_test.go
  internal/blockprocessor/test_util.go
  internal/blockprocessor/useradmin_tx_validator_test.go
  internal/blockprocessor/validator_test.go
  internal/identity/db_entries.go
  internal/identity/db_entries_test.go
  internal/identity/querier_test.go
  internal/worldstate/db.go
  internal/worldstate/leveldb/commit_and_query.go
  internal/worldstate/leveldb/commit_and_query_test.go
Labels: bug

#8 Create index entries
  internal/stateindex/index_entries.go
  internal/stateindex/index_entries_test.go
  internal/worldstate/db.go
  internal/worldstate/leveldb/commit_and_query.go
  internal/worldstate/leveldb/commit_and_query_test.go
Labels: query support

#118 sync write to state trie store
  internal/mptrie/store/update_and_query.go
Labels: bug

#84 Integrate raft node
  internal/bcdb/db.go
  internal/bcdb/mocks/db.go
  internal/bcdb/transaction_processor.go
  internal/bcdb/transaction_processor_test.go
  internal/blockcreator/blockcreator.go
  internal/blockcreator/blockcreator_test.go
  internal/blockcreator/mocks/replicator.go
  internal/comm/httptransport.go
  internal/errors/errors.go
  internal/replication/blockreplicator.go
  internal/replication/blockreplicator_test.go
  internal/replication/storage.go
  internal/replication/storage_test.go
  internal/replication/utils.go
  pkg/logger/logger.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: replication

#128 Missing zap duration encoder
  pkg/logger/logger.go
Labels: bug

#124 Improving MPTrie performance
  internal/mptrie/mptrie.go
  internal/mptrie/store/update_and_query.go
  internal/mptrie/store/update_and_query_test.go
Labels: performance

#129 Parallel verification of signatures in a block
  internal/bcdb/ledger_query_procesor_test.go
  internal/bcdb/provenance_query_processor_test.go
  internal/bcdb/transaction_processor_test.go
  internal/bcdb/worldstate_query_processor_test.go
  internal/blockprocessor/data_tx_validator.go
  internal/blockprocessor/data_tx_validator_test.go
  internal/blockprocessor/validator.go
Labels: performance

#29 Create index db & commit index entries
  internal/blockprocessor/committer.go
  internal/blockprocessor/committer_test.go
Labels: query support
