Repository hyperledger-labs/orion-server, pull requests merged in 2021-06, with the labels that each got.

#27 Add With() to logger
  pkg/logger/logger.go
  pkg/logger/logger_test.go
Labels: enhancement

#90 change proto messages to make it fit for cURL
  internal/bcdb/db.go
  internal/bcdb/ledger_query_procesor.go
  internal/bcdb/mocks/db.go
  internal/bcdb/transaction_processor.go
  internal/bcdb/transaction_processor_test.go
  internal/httphandler/config_request_handler_test.go
  internal/httphandler/data_request_handler_test.go
  internal/httphandler/db_request_handler_test.go
  internal/httphandler/ledger_request_handler_test.go
  internal/httphandler/provenance_request_handler.go
  internal/httphandler/provenance_request_handler_test.go
  internal/httphandler/users_request_handler_test.go
  internal/httphandler/utils_test.go
  pkg/server/mock/rest_client.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/types/response.pb.go
  protos/response.proto
Labels: documentation

#91 use lower case characters in keys for the json request/response
  internal/bcdb/db.go
  internal/bcdb/ledger_query_procesor_test.go
  internal/bcdb/transaction_processor.go
  internal/bcdb/transaction_processor_test.go
  internal/bcdb/worldstate_query_processor_test.go
  internal/blockcreator/blockcreator.go
  internal/blockcreator/blockcreator_test.go
  internal/blockprocessor/committer.go
  internal/blockprocessor/committer_test.go
  internal/blockprocessor/config_tx_validator.go
  internal/blockprocessor/config_tx_validator_test.go
  internal/blockprocessor/data_tx_validator.go
  internal/blockprocessor/data_tx_validator_test.go
  internal/blockprocessor/dbadmin_tx_validator.go
  internal/blockprocessor/dbadmin_tx_validator_test.go
  internal/blockprocessor/processor_test.go
  internal/blockprocessor/useradmin_tx_validator.go
  internal/blockprocessor/useradmin_tx_validator_test.go
  internal/blockprocessor/validator.go
  internal/blockprocessor/validator_test.go
  internal/blockstore/commit_and_query.go
  internal/blockstore/commit_and_query_test.go
  internal/blockstore/open_test.go
  internal/httphandler/config_request_handler.go
  internal/httphandler/config_request_handler_test.go
  internal/httphandler/data_request_handler.go
  internal/httphandler/data_request_handler_test.go
  internal/httphandler/db_request_handler.go
  internal/httphandler/db_request_handler_test.go
  internal/httphandler/ledger_request_handler.go
  internal/httphandler/ledger_request_handler_test.go
  internal/httphandler/provenance_request_handler.go
  internal/httphandler/provenance_request_handler_test.go
  internal/httphandler/users_request_handler.go
  internal/httphandler/users_request_handler_test.go
  internal/httphandler/utils.go
  internal/httphandler/utils_test.go
  internal/identity/db_entries.go
  internal/identity/db_entries_test.go
  internal/identity/querier.go
  internal/identity/querier_test.go
  internal/mtree/hash.go
  internal/mtree/hash_test.go
  internal/mtree/mtree_test.go
  internal/txreorderer/txreorderer.go
  internal/txreorderer/txreorderer_test.go
  internal/worldstate/leveldb/commit_and_query_test.go
  pkg/cryptoservice/signer_test.go
  pkg/server/mock/rest_client.go
  pkg/server/server_test.go
  pkg/types/block_and_transaction.pb.go
  pkg/types/configuration.pb.go
  pkg/types/query.pb.go
  pkg/types/response.pb.go
  protos/block_and_transaction.proto
  protos/configuration.proto
  protos/query.proto
  protos/response.proto
  test/setup/cluster_setup_test.go
Labels: documentation

#11 Integrate transport into replicator and transaction processor
  internal/bcdb/db.go
  internal/bcdb/mocks/db.go
  internal/bcdb/transaction_processor.go
  internal/bcdb/transaction_processor_test.go
  internal/blockcreator/blockcreator.go
  internal/blockprocessor/processor.go
  internal/blockprocessor/processor_test.go
  internal/comm/httptransport.go
  internal/replication/blockreplicator.go
  internal/replication/blockreplicator_test.go
  pkg/server/server.go
  test/setup/server_setup.go
Labels: replication

#82 Consensus metadata proto
  pkg/types/block_and_transaction.pb.go
  protos/block_and_transaction.proto
Labels: replication

#83 Raft config extension
  config/config.go
  config/shared_config.go
  config/shared_config_test.go
  config/testdata/3node-shared-config-bootstrap.yml
  internal/bcdb/transaction_processor.go
  internal/bcdb/transaction_processor_test.go
  pkg/server/server_test.go
  pkg/types/configuration.pb.go
  protos/configuration.proto
  test/setup/cluster_setup.go
Labels: replication
